version: "3.9"

services:
  app:
    image: lahiru98s/devops-blog:latest
    container_name: devops-blog
    environment:
      # Required: set a strong secret in production
      - JWT_SECRET=${JWT_SECRET}
      # Optional: first-run admin credentials (used only if DB is empty)
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeMe!}
      # Internal web port inside the container (matches image default)
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      # Persist the SQLite database file
      - db-data:/app/db
      # Persist uploaded media files
      - uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:8080/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  uploads:

