version: "3.9"

services:
  app:
    build: .
    image: devops-blog:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      - db-data:/app/db
      - uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  db-data:
  uploads:

